# Project configuration file
# Overrides any configuration set in the proj_master_config.yaml file
# Careful when changing the structure of this file

# Project
project:
  name: Example Project                   # Project long name
  alias: example_project                  # Project alias for folder structure
  format: 4K DCI                          # Informative, not used in RST functions
  width: 4096                             # Informative, not used in RST functions
  height: 2160                            # Informative, not used in RST functions
  fps: 24                                 # Informative, not used in RST functions
  ocio: aces_1.2                          # Informative, not used in RST functions

  # Project folders
  path: .                                 # This folder need to be created manually. In this example project path is set to where the rst_gui.py lives
  tmp_path: tmp

  # Add sequences
  sequences:                              # Sequences prefixes to be used. The list of sequence get overwriten by local project config files
    - seq01
    - seq02
    - seq03


# Kitsu
# Any folder will be created on the project folder
kitsu:
  server: 'http://192.168.100.80:8800'    # Your Kitsu server URL

  #Defaults for shot creation
  shot_interval: 10
  shot_padding: 3


#Resolve
resolve:
  vfx_plate_trk_name: SRC                 # Track used to pull source shot plates
  vfx_shots_trk_name: VFX                 # Track used to update VFX takes (Not currently Implemented)
  vfx_shot_start_frame: 1001              # Staring frame including handles
  vfx_shot_handles: 8                     # Amount of handles before cut in. In this case the first frame of the cut will be 1009
  default_render_preset: exr_plates       # Name of the Resolve Delivery Preset. By default is set to a custom one created to render Plates EXR sequences


#Naming Conventions
naming_convention:
  # Categories (shotid, version, image)
  shotid:
    pfix: <sequence>_                     # Prefix to e used in shot names before the number. Change this to "<sequence>" to use the sequence name as the prefix
    pad: 3                                # Shot number padding
    interval: 10                          # Default interval between shot numbers

  # Default Version Padding
  version:
    pad: 3

  # Various image naming convention
  image:
    pad: 4

    # Presets
    plate:
      path: images/elem                   # Directory structure with a shot folder
      file: <shotid>.<track_name>         # Plate Directory and Clip names

#    openclip:
#      path: images/openclip
#      file: <shotid>
