---
presets:

  project:
    folders:
    - name: config
      default: true
      folders:
      - name: kitsu
        default: true
    - name: editorial
      default: true
      folders:
      - name: resolve
        default: true

  seq:
    folders:
    - name: assets
      default: false
    - name: images
      default: false
      folders:
      - name: comp
        default: false
      - name: elem
        default: false
      - name: render
        default: false
      - name: reference
        default: false
    - name: reference
      default: false

  shot:
    folders:
      - name: images
        default: true
        folders:
          - name: comp
            default: true
          - name: elem
            default: true
          - name: render
            default: true
          - name: pcomp
            default: false
          - name: reference
            default: true
      - name: movies
        default: true

  elem:
    folders:
    - name: plates
      default: false
    - name: reference
      default: false

  apps:
    folders:
    - name: blender
      default: false
    - name: fusion
      default: false
    - name: houdini
      default: false
    - name: maya
      default: false
    - name: mocha
      default: false
    - name: nuke
      default: false
    - name: gaffer
      default: false
