# This file sets the default configuration of a project
# Careful when changing the structure of this file

# Project
project:
  name: Default Project                   # Project long name
  alias: default_project                  # Project alias for folder structure
  format: 2K DCI                          # Informative, not used in RST functions
  width: 2048                             # Informative, not used in RST functions
  height: 1080                            # Informative, not used in RST functions
  fps: 24                                 # Informative, not used in RST functions
  ocio: aces_1.2                          # Currently not used

  # Project folders
  path: /path/to/project/directory        # This folder need to be created manually. Overrided by individual project config.yaml
  tmp_path: tmp                           # This folder need to be created manually

  # Add sequences
  sequences:                              # Sequences prefixes to be used. The list of sequence get overwriten by local project config files
    - tst                                 # Sequence folder are created unde the project name

# Kitsu
# Any folder will be created on the project folder
kitsu:
  server: 'http://192.168.100.80:8800'    # Your Kitsu server URL
  config_folder: config                   # This folder may need to be created manually
  thumbnail_folder: thumbnails            # Directory to save thumbnails for Kitsu shot entries. This folder is cretated automatically

  # Defaults for shot creation
  shot_create_task: Comp                  # This need to be a valid task name in Kitsu
  shot_create_status: RTS                 # Ready to start. This need to be a valid status name in Kitsu
  shot_create_comment: Version 00
  shot_interval: 10
  shot_padding: 4
  kitsu_data: ['Project',
               'Sequence',
               'Name',
               'Description',
               'Nb Frames',
               'Frame In',
               'Frame Out',
               'Artist',
               'Status',
               'Notes',
               'Focal',
               'FStop']

#Resolve
resolve:
  vfx_plate_trk_name: SRC                 # Track used to pull source shot plates
  vfx_shots_trk_name: VFX                 # Track used to update VFX takes (Not currently Implemented)
  vfx_shot_start_frame: 1001              # Staring frame including handles
  vfx_shot_handles: 8                     # Amount of handles before cut in. In this case the first frame of the cut will be 1009
  default_render_preset: exr_plates       # Name of the Resolve Delivery Preset. By default is set to a custom one created to render Plates EXR sequences

  clip colors:                            # The selected color will be used to set shotids in the timeline
    - Orange
    - Apricot
    - Yellow
    - Lime
    - Olive
    - Green
    - Teal
    - Navy
    - Blue
    - Purple
    - Violet
    - Pink
    - Tan
    - Beige
    - Brown
    - Chocolate
  flag colors:                             # Flags Colors will be use for Markers colors as well as to select what shots get sent to the delivery page for plate rendering
    - Blue
    - Cyan
    - Green
    - Yellow
    - Red
    - Pink
    - Purple
    - Fuchsia
    - Rose
    - Lavender
    - Sky
    - Mint
    - Lemon
    - Sand
    - Cocoa
    - Cream
    - Frame.io
  odt:
    - Rec.709
    - ACEScg - CSC
    - ACEScct - CSC
    - ACEScc - CSC
    - sRGB
    - sRGB (Linear) - CSC
  id_as:
    - Clip Name
    - Versions
    - Markers


  vfx_tasks:
    - elem
    - roto
    - comp
    - light
    - layout
    - fx


#Naming Conventions
naming_convention:
  # Categories (shotid, version, image, paths)
  shotid:
    pfix: sht                               # Prefix to be used in shot names before the number. Change this to "<sequence>" to use the sequence name as the prefix
    pad: 4                                  # Shot number padding
    interval: 10                            # Interval between shot numbers

  # Default Version Padding
  version:
    pad: 2

  # Various image naming convention
  image:
    pad: 4

    # Presets
    # Plate
    plate:
      path: images/elem                     # Directory structure with a shot folder
      file: <shotid>.<track_name>           # Plate Directory and Clip names

    # Openclip
#    openclip:
#      path: images/openclip
#      file: <shotid>.clip

  # Paths
  paths:
    # Presets
    plates:
      path: <proj_root>/<proj>/<seq>/<shotid>

    openclips:
      path: <proj_root>/<proj>/<seq>/openclip