---
# Folder structure presets used by proj_utils.py ProjectUtils.mk_tree method
# Currently not used
presets:
  project:
    folders:
    - name: config
      default: true

  level:
    folders:
    - name: config
      default: true
    - name: images
      default: true

  seq:
    folders:
    - name: images
      default: false
      folders:
      - name: elem
        default: true

  elem:
    folders:
    - name: plates
      default: true
