# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'rst_ui.qt6.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_main_window(object):
    def setupUi(self, main_window):
        if not main_window.objectName():
            main_window.setObjectName(u"main_window")
        main_window.resize(339, 840)
        self.frame_shots = QFrame(main_window)
        self.frame_shots.setObjectName(u"frame_shots")
        self.frame_shots.setGeometry(QRect(4, 10, 331, 531))
        font = QFont()
        font.setFamilies([u"Open Sans"])
        self.frame_shots.setFont(font)
        self.frame_shots.setFrameShape(QFrame.StyledPanel)
        self.frame_shots.setFrameShadow(QFrame.Raised)
        self.messages_TE = QTextEdit(self.frame_shots)
        self.messages_TE.setObjectName(u"messages_TE")
        self.messages_TE.setGeometry(QRect(10, 110, 311, 211))
        font1 = QFont()
        font1.setFamilies([u"Courier 10 Pitch"])
        font1.setPointSize(8)
        self.messages_TE.setFont(font1)
        self.messages_TE.setReadOnly(True)
        self.seq_LB = QLabel(self.frame_shots)
        self.seq_LB.setObjectName(u"seq_LB")
        self.seq_LB.setGeometry(QRect(10, 70, 71, 26))
        self.seq_LB.setFont(font)
        self.seq_CB = QComboBox(self.frame_shots)
        self.seq_CB.setObjectName(u"seq_CB")
        self.seq_CB.setGeometry(QRect(110, 70, 211, 32))
        self.seq_CB.setFont(font)
        self.proj_LB = QLabel(self.frame_shots)
        self.proj_LB.setObjectName(u"proj_LB")
        self.proj_LB.setEnabled(False)
        self.proj_LB.setGeometry(QRect(10, 10, 71, 26))
        font2 = QFont()
        font2.setFamilies([u"Open Sans"])
        font2.setPointSize(11)
        self.proj_LB.setFont(font2)
        self.proj_TE = QLineEdit(self.frame_shots)
        self.proj_TE.setObjectName(u"proj_TE")
        self.proj_TE.setEnabled(False)
        self.proj_TE.setGeometry(QRect(110, 10, 211, 21))
        self.proj_TE.setFont(font)
        self.root_TE = QLineEdit(self.frame_shots)
        self.root_TE.setObjectName(u"root_TE")
        self.root_TE.setEnabled(False)
        self.root_TE.setGeometry(QRect(110, 40, 211, 21))
        self.root_TE.setFont(font)
        self.rootj_LB = QLabel(self.frame_shots)
        self.rootj_LB.setObjectName(u"rootj_LB")
        self.rootj_LB.setEnabled(False)
        self.rootj_LB.setGeometry(QRect(10, 40, 41, 26))
        self.rootj_LB.setFont(font)
        self.resolveshots_BT = QPushButton(self.frame_shots)
        self.resolveshots_BT.setObjectName(u"resolveshots_BT")
        self.resolveshots_BT.setGeometry(QRect(170, 330, 151, 31))
        palette = QPalette()
        brush = QBrush(QColor(104, 52, 52, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.resolveshots_BT.setPalette(palette)
        self.resolveshots_BT.setFont(font)
        self.clipcolor_CB = QComboBox(self.frame_shots)
        self.clipcolor_CB.setObjectName(u"clipcolor_CB")
        self.clipcolor_CB.setGeometry(QRect(170, 450, 151, 32))
        self.clipcolor_CB.setFont(font)
        self.clipcolor_LB = QLabel(self.frame_shots)
        self.clipcolor_LB.setObjectName(u"clipcolor_LB")
        self.clipcolor_LB.setGeometry(QRect(10, 450, 151, 26))
        self.clipcolor_LB.setFont(font)
        self.clipcolor_LB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.flag_CB = QComboBox(self.frame_shots)
        self.flag_CB.setObjectName(u"flag_CB")
        self.flag_CB.setGeometry(QRect(170, 490, 151, 32))
        self.flag_CB.setFont(font)
        self.flag_LB = QLabel(self.frame_shots)
        self.flag_LB.setObjectName(u"flag_LB")
        self.flag_LB.setGeometry(QRect(20, 490, 141, 26))
        self.flag_LB.setFont(font)
        self.flag_LB.setLayoutDirection(Qt.LeftToRight)
        self.flag_LB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.export_csv_BT = QPushButton(self.frame_shots)
        self.export_csv_BT.setObjectName(u"export_csv_BT")
        self.export_csv_BT.setGeometry(QRect(10, 370, 151, 32))
        self.export_csv_BT.setFont(font)
        self.clearRIDs_BT = QPushButton(self.frame_shots)
        self.clearRIDs_BT.setObjectName(u"clearRIDs_BT")
        self.clearRIDs_BT.setGeometry(QRect(170, 370, 151, 32))
        self.clearRIDs_BT.setFont(font)
        self.createas_CB = QComboBox(self.frame_shots)
        self.createas_CB.setObjectName(u"createas_CB")
        self.createas_CB.setGeometry(QRect(170, 410, 151, 32))
        self.createas_CB.setFont(font)
        self.resolveid_LB = QLabel(self.frame_shots)
        self.resolveid_LB.setObjectName(u"resolveid_LB")
        self.resolveid_LB.setGeometry(QRect(20, 410, 141, 26))
        self.resolveid_LB.setFont(font)
        self.resolveid_LB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.start_index_CKB = QCheckBox(self.frame_shots)
        self.start_index_CKB.setObjectName(u"start_index_CKB")
        self.start_index_CKB.setEnabled(True)
        self.start_index_CKB.setGeometry(QRect(10, 334, 101, 20))
        self.start_index_CKB.setFont(font)
        self.start_index_CKB.setChecked(False)
        self.start_index_LE = QLineEdit(self.frame_shots)
        self.start_index_LE.setObjectName(u"start_index_LE")
        self.start_index_LE.setGeometry(QRect(120, 330, 41, 31))
        self.start_index_LE.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frame_plates = QFrame(main_window)
        self.frame_plates.setObjectName(u"frame_plates")
        self.frame_plates.setGeometry(QRect(4, 650, 331, 131))
        self.frame_plates.setFont(font)
        self.frame_plates.setFrameShape(QFrame.StyledPanel)
        self.frame_plates.setFrameShadow(QFrame.Raised)
        self.renderjobs_BT = QPushButton(self.frame_plates)
        self.renderjobs_BT.setObjectName(u"renderjobs_BT")
        self.renderjobs_BT.setEnabled(True)
        self.renderjobs_BT.setGeometry(QRect(170, 90, 151, 32))
        self.renderjobs_BT.setFont(font)
        self.odt_CB = QComboBox(self.frame_plates)
        self.odt_CB.setObjectName(u"odt_CB")
        self.odt_CB.setGeometry(QRect(170, 50, 151, 32))
        self.odt_CB.setFont(font)
        self.odt_LB = QLabel(self.frame_plates)
        self.odt_LB.setObjectName(u"odt_LB")
        self.odt_LB.setGeometry(QRect(10, 50, 151, 26))
        self.odt_LB.setFont(font)
        self.odt_LB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.job_presets_LB = QLabel(self.frame_plates)
        self.job_presets_LB.setObjectName(u"job_presets_LB")
        self.job_presets_LB.setGeometry(QRect(10, 10, 151, 26))
        self.job_presets_LB.setFont(font)
        self.job_presets_LB.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.job_presets_CB = QComboBox(self.frame_plates)
        self.job_presets_CB.setObjectName(u"job_presets_CB")
        self.job_presets_CB.setGeometry(QRect(170, 10, 151, 32))
        self.job_presets_CB.setFont(font)
        self.close_BT = QPushButton(main_window)
        self.close_BT.setObjectName(u"close_BT")
        self.close_BT.setGeometry(QRect(174, 795, 151, 32))
        self.close_BT.setFont(font)
        self.dryrun_CKB = QCheckBox(main_window)
        self.dryrun_CKB.setObjectName(u"dryrun_CKB")
        self.dryrun_CKB.setGeometry(QRect(43, 800, 81, 20))
        self.dryrun_CKB.setFont(font)
        self.dryrun_CKB.setChecked(True)
        self.frame_kitsu = QFrame(main_window)
        self.frame_kitsu.setObjectName(u"frame_kitsu")
        self.frame_kitsu.setGeometry(QRect(4, 550, 331, 91))
        self.frame_kitsu.setFrameShape(QFrame.StyledPanel)
        self.frame_kitsu.setFrameShadow(QFrame.Raised)
        self.kitsushots_BT = QPushButton(self.frame_kitsu)
        self.kitsushots_BT.setObjectName(u"kitsushots_BT")
        self.kitsushots_BT.setGeometry(QRect(170, 50, 151, 32))
        palette1 = QPalette()
        brush1 = QBrush(QColor(55, 88, 55, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        self.kitsushots_BT.setPalette(palette1)
        self.kitsushots_BT.setFont(font)
        self.kitsuURL = QLineEdit(self.frame_kitsu)
        self.kitsuURL.setObjectName(u"kitsuURL")
        self.kitsuURL.setGeometry(QRect(10, 10, 311, 31))
        self.kitsuURL.setAlignment(Qt.AlignCenter)

        self.retranslateUi(main_window)

        QMetaObject.connectSlotsByName(main_window)
    # setupUi

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QCoreApplication.translate("main_window", u"main_window", None))
        self.seq_LB.setText(QCoreApplication.translate("main_window", u"Sequence", None))
        self.proj_LB.setText(QCoreApplication.translate("main_window", u"Project", None))
        self.proj_TE.setText("")
        self.root_TE.setText("")
        self.rootj_LB.setText(QCoreApplication.translate("main_window", u"Path", None))
        self.resolveshots_BT.setText(QCoreApplication.translate("main_window", u"Create Resolve IDs", None))
        self.clipcolor_LB.setText(QCoreApplication.translate("main_window", u"Clip Color", None))
        self.flag_LB.setText(QCoreApplication.translate("main_window", u"Flag Color", None))
        self.export_csv_BT.setText(QCoreApplication.translate("main_window", u"Export CSV", None))
        self.clearRIDs_BT.setText(QCoreApplication.translate("main_window", u"Clear Resolve IDs", None))
        self.resolveid_LB.setText(QCoreApplication.translate("main_window", u"Resolve IDs as", None))
        self.start_index_CKB.setText(QCoreApplication.translate("main_window", u"Start Index", None))
        self.start_index_LE.setText(QCoreApplication.translate("main_window", u"10", None))
        self.renderjobs_BT.setText(QCoreApplication.translate("main_window", u"Create Plate Jobs", None))
        self.odt_LB.setText(QCoreApplication.translate("main_window", u"Render ODT", None))
        self.job_presets_LB.setText(QCoreApplication.translate("main_window", u"Job Presets", None))
        self.close_BT.setText(QCoreApplication.translate("main_window", u"Close", None))
        self.dryrun_CKB.setText(QCoreApplication.translate("main_window", u"Dry Run", None))
        self.kitsushots_BT.setText(QCoreApplication.translate("main_window", u"Create Kitsu Shots", None))
#if QT_CONFIG(tooltip)
        self.kitsuURL.setToolTip(QCoreApplication.translate("main_window", u"Kitsu URL", None))
#endif // QT_CONFIG(tooltip)
        self.kitsuURL.setText(QCoreApplication.translate("main_window", u"http://192.168.100.80:8800", None))
    # retranslateUi

